import os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from agents.state import PipelineState


def _make_bar_chart(data: dict, title: str, filepath: str, color: str = "#5fc9c0", horizontal: bool = False):
    if not data:
        return False
    labels = list(data.keys())
    values = list(data.values())
    plt.figure(figsize=(7, 5))
    if horizontal:
        plt.barh(labels, values, color=color)
        plt.gca().invert_yaxis()
    else:
        plt.bar(labels, values, color=color)
        plt.xticks(rotation=20, ha="right")
    plt.title(title)
    plt.tight_layout()
    plt.savefig(filepath)
    plt.close()
    return True


def dashboard_agent(state: PipelineState) -> PipelineState:
    """
    Builds a dashboard dynamically based on whatever the Analysis Agent
    produced. Adapts its layout and charts to whichever fields actually
    exist in analysis_results, instead of a fixed hardcoded layout.
    """
    print("🖥️ Dashboard Agent: starting...")

    try:
        results = state.get("analysis_results") or {}
        domain = results.get("domain", "unknown dataset")
        dataset_name = os.path.splitext(os.path.basename(state.get("raw_data_path", "dataset")))[0]

        assets_dir = "assets"
        os.makedirs(assets_dir, exist_ok=True)

        # Build stat cards only for fields that actually exist
        stat_cards = []
        if "total_revenue" in results:
            stat_cards.append((f"Total {results.get('revenue_label', 'Revenue').title()}", f"${results['total_revenue']:,.2f}"))
        if "total_rows" in results:
            stat_cards.append(("Total Records", f"{results['total_rows']:,}"))
        if "total_quantity" in results:
            stat_cards.append((f"Total {results.get('quantity_label', 'Quantity').title()}", f"{results['total_quantity']:,}"))
        if "avg_revenue" in results:
            stat_cards.append(("Average Value", f"${results['avg_revenue']:,.2f}"))

        # Build charts only for fields that actually exist
        charts_html = ""
        chart_count = 0

        if results.get("by_category"):
            path = f"{assets_dir}/{dataset_name}-chart-category.png"
            if _make_bar_chart(results["by_category"], f"By {results.get('category_label', 'Category').title()}", path, "#5fc9c0"):
                charts_html += f'<div class="chart-card"><p class="chart-title">By {results.get("category_label","Category").title()}</p><img src="../{path}"></div>'
                chart_count += 1

        if results.get("by_region"):
            path = f"{assets_dir}/{dataset_name}-chart-region.png"
            if _make_bar_chart(results["by_region"], f"By {results.get('region_label', 'Region').title()}", path, "#f2a65a"):
                charts_html += f'<div class="chart-card"><p class="chart-title">By {results.get("region_label","Region").title()}</p><img src="../{path}"></div>'
                chart_count += 1

        if results.get("top_items"):
            path = f"{assets_dir}/{dataset_name}-chart-top-items.png"
            if _make_bar_chart(results["top_items"], "Top 5 Items", path, "#e1654a", horizontal=True):
                charts_html += f'<div class="chart-card"><p class="chart-title">Top 5 Items</p><img src="../{path}"></div>'
                chart_count += 1

        stats_html = "".join(
            f'<div class="stat-card"><p class="stat-label">{label}</p><p class="stat-value">{value}</p></div>'
            for label, value in stat_cards
        )

        error_banner = ""
        if state.get("error"):
            error_banner = f'<div class="error-banner">⚠️ Note: {state["error"]}</div>'

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{domain.title()} — Dashboard</title>
<link rel="stylesheet" href="dashboard.css">
</head>
<body>
<div class="grid-overlay" aria-hidden="true"></div>
<header class="dash-header">
  <p class="eyebrow">Auto-generated Dashboard &middot; Domain: {domain.title()}</p>
  <h1>{dataset_name.replace('_', ' ').title()}</h1>
  <p class="dash-sub">Generated automatically by the Dashboard Agent based on the detected domain and available data.</p>
</header>
<main>
  {error_banner}
  <section class="stats-row">{stats_html}</section>
  <section class="charts-grid">{charts_html}</section>
</main>
<footer class="colophon">
  <p>Generated by the Multi-Agent Business Data Pipeline &middot; Domain Configuration + Dashboard Agents</p>
</footer>
</body>
</html>"""

        output_path = f"dashboard/{dataset_name}-dashboard.html"
        os.makedirs("dashboard", exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)

        print(f"🖥️ Dashboard Agent: done. Saved to {output_path} ({chart_count} charts, {len(stat_cards)} stats)")

        state["dashboard_html"] = output_path
        state["current_step"] = "dashboard_built"

    except Exception as e:
        print(f"⚠️ Dashboard Agent failed: {e}")
        state["error"] = f"Dashboard generation failed: {str(e)}"
        state["dashboard_html"] = None

    return state